[sim]
version = "5.1.0"
ext-folder = [
    "./packages/sim-exts",
]

[sim.settings]
raytracing-motion = false
cpu-performance-mode = true

[sim.exts]
isaacsim.code_editor.vscode = true
pow.workcell.camera = true
