[sim]
ext-folder = []
isaacsim_ros_ws = ""
ros_distro = "humble" # support: humble, jazzy

[[sim.profiles]]
name = "default"
cpu_performance_mode = true
headless = false
extensions = ["isaacsim.code_editor.vscode"]
raw_args = ["--/renderer/raytracingMotion/enabled=false"]

[[sim.profiles]]
name = "factory-scene"
open_scene_path = ""
