[project]
name = "isaac-powerpack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "isaacsim[all,extscache]==5.1.0",
]

[[tool.uv.index]]
url = "https://pypi.nvidia.com/"
