# Extension configuration file.
# Visit the "Extension configuration file (extension.toml)" section for more details:
# https://docs.omniverse.nvidia.com/kit/docs/kit-manual/latest/guide/extensions_advanced.html
#

[core]
reloadable = true
order = 0

[package]
version = "0.1.0"
category = "simulation"
title = "Isaac Powerpack Sim Camera"
description = "Spawn cameras, generate the required ROS 2 Omnigraph nodes, and control their movement via the Foxglove Isaac Powerpack."
authors = ["Be Munin"]
repository = "https://github.com/bemunin/isaac-powerpack"
keywords = ["foxglove","ros2"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
"omni.graph" = {}
"omni.graph.tools" = {}
"omni.kit.uiapp" = {}

# define the Python module that the extension provides
[[python.module]]
name = "pow.workcell.camera"

# define the Python module for tests
[[python.module]]
name = "pow.workcell.camera.tests"

[settings]
exts."pow.workcell.camera".timeout = 5

# disable startup test
[[test]]
name = "startup"
enabled = false

[[test]]
enabled = true
dependencies = [
    "omni.kit.test",
]
