[project]
name = "pow-cli"
version = "0.0.1"
description = "Command line interface for Isaac Powerpack"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "click>=8.1.7",
    "toml>=0.10.2",
]
license="Apache-2.0"

[project.scripts]
pow = "pow.main:pow"